services:
  - type: web
    name: pdf-split-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: PDF_DIRECTORY
        value: "./pdf_files"  # Adjust this to the path where PDFs are stored on Render
